apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: kurs2tarsovan/nginxbalancer:latest  # Укажите свой образ Nginx
          name: nginx-reverseproxy
          ports:
            - containerPort: 80
          resources:
          limits:
            memory: "1024Mi"
            cpu: "2"
          requests:
            memory: "512Mi"
            cpu: "1"
