apiVersion: v1
data:
  nginx.conf: |
    # Запускать в качестве менее привилегированного пользователя по соображениям безопасности..
    user nginx;

    # Значение auto устанавливает число максимально доступных ядер CPU,
    # чтобы обеспечить лучшую производительность.
    worker_processes    auto;

    events { worker_connections 1024; }

    http {
        server {
            listen 80;

            # Фронтенд
            location / {
                proxy_pass http://frontend:80;
            }
            # Прокси запросов к API
            location /api {
                proxy_pass http://backend:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
